[tool.poetry]
name = "first-flet-app"
version = "0.1.0"
description = ""
authors = ["dilshodev3234 <absaitovdev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flet = "^0.23.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
