version: '3.11'


services:
  bot:
    image: dilshodev/echo-bot
    restart: always
    container_name: my_bot
    environment:
      BOT_TOKEN: 5314436530:AAGNzpSNa3cAk2H-1CIDhGHfhJ0PisKEWXM
      DB_NAME: postgres
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py


  pg:
    image: postgres
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:

