version: '3.11'


services:
  bot:
    build: .
    restart: always
    container_name: kwork_bot
    environment:
      BOT_TOKEN: 6494569838:AAHuoZXbs_yJIEmWzw7v4Jjahy5uItJvibU
      DB_NAME: kwork_db
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  pg:
    image: postgres
    restart: always
    container_name: kwork_db
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
  dbdata6: