# Generated by Django 5.0.4 on 2024-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
