version: '3.11'

services:
  bot:
    build: .
#    image: dilshodev/echo-bot
    restart: always
    container_name: my_bot
    environment:
      BOT_TOKEN: 6385276113:AAFTkoPVDR3xsV6tQ8PF-4n0h_s20RI6KWI
      DB_NAME: postgres
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py


  pg:
    image: postgres:alpine
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
