# Generated by Django 5.0.3 on 2024-04-18 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_category_options_alter_product_options_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
