# Generated by Django 5.0.7 on 2024-08-04 18:10

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.category'),
        ),
    ]
