# Generated by Django 5.0.7 on 2024-08-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_category_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='owner',
            new_name='parent',
        ),
    ]
