mig:
	python3 manage.py makemigrations
	python3 manage.py migrate

user:
	python3 manage.py createsuperuser

run:
	python3 manage.py runserver

make:
	django-admin makemessage -l en
	django-admin makemessage -l ru
	django-admin makemessage -l uz

compile:
	django-admin compilemessages