mig:
	python3 manage.py makemigrations
	python3 manage.py migrate

create_user:
	python3 manage.py createsuperuser

run:
	python3 manage.py runserver

loaddata:
	python3 manage.py loaddata masjids transaction_type role

