mig:
	python3 manage.py makemigrations
	python3 manage.py migrate

user:
	python3 manage.py createsuperuser

make:
	django-admin makemessages -l en
	django-admin makemessages -l ru
	django-admin makemessages -l uz

compile:
	django-admin compilemessages



